services:
  - type: web
    name: event-system   # you can change this if you want
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: JWT_SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false


